filter {
  if [log_type] == "suricata" {
    if [event_type] in ["alert", "flow", "dns", "http", "tls", "fileinfo"] {
      mutate { replace => { "log_source_normalized" => "NSM:Flow" } }
    } else {
      mutate { replace => { "log_source_normalized" => "NSM:Connections" } }
    }

    mutate {
      add_field => { "event.category" => "network" }
      add_field => { "event.type" => "connection" }
    }
  }

  if [log_type] == "process_alarm" {
    mutate {
      replace => { "log_source_normalized" => "ics:process_alarm" }
      add_field => { "event.category" => "process" }
      add_field => { "event.type" => "alarm" }
    }
  }

  if [log_type] == "plc_app" {
    mutate {
      replace => { "log_source_normalized" => "ics:plc_app" }
      add_field => { "event.category" => "process" }
      add_field => { "event.type" => "state" }
    }
  }

  if [log_type] == "hmi_catalina" {
    mutate {
      replace => { "log_source_normalized" => "hmi:catalina" }
      add_field => { "event.category" => "application" }
      add_field => { "event.type" => "info" }
    }
  }

  if [log_type] == "pacct" {
    mutate {
      replace => { "log_source_normalized" => "linux:pacct" }
      add_field => { "event.category" => "process" }
      add_field => { "event.type" => "history" }
    }
  }

  if ![log_source_normalized] {
    mutate { add_field => { "log_source_normalized" => "unknown" } }
  }
}
