filter {
  translate {
    source => "log_source_normalized"
    target => "mitre_dc_candidates"
    dictionary_path => "/usr/share/logstash/mitre_mapping/log_source_to_dc.yml"
    fallback => "unknown"
    exact => true
  }

  mutate {
    split => { "mitre_dc_candidates" => "," }
  }

  ruby {
    path => "/usr/share/logstash/mitre_mapping/keyword_tagger.rb"
    script_params => {
      "keywords_path" => "/usr/share/logstash/mitre_mapping/dc_keywords.json"
    }
  }
}
