output {
  if [log_type] in ["suricata", "suricata_fast", "suricata_engine", "suricata_app", "suricata_stdio"] {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "ics-suricata-%{+YYYY.MM.dd}"
      ilm_enabled => false
    }
  } else if [log_type] == "audit" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "ics-audit-%{+YYYY.MM.dd}"
      ilm_enabled => false
    }
  } else if [log_type] == "auth" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "ics-auth-%{+YYYY.MM.dd}"
      ilm_enabled => false
    }
  } else if [log_type] in ["process_alarm", "plc_app", "modbus_io", "sim_process", "sim_error", "openplc_debug"] {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "ics-process-%{+YYYY.MM.dd}"
      ilm_enabled => false
    }
  } else if [log_type] in ["hmi_catalina", "hmi_supervisor"] {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "ics-hmi-%{+YYYY.MM.dd}"
      ilm_enabled => false
    }
  } else if [log_type] in ["netfilter", "ulogd"] {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "ics-netfilter-%{+YYYY.MM.dd}"
      ilm_enabled => false
    }
  } else if [log_type] in ["nginx_access", "nginx_error"] {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "ics-nginx-%{+YYYY.MM.dd}"
      ilm_enabled => false
    }
  } else if [log_type] in ["ews_desktop", "ews_supervisord", "sim_supervisord", "router_supervisord"] {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "ics-ews-%{+YYYY.MM.dd}"
      ilm_enabled => false
    }
  } else if [log_type] == "fw_app" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "ics-router-%{+YYYY.MM.dd}"
      ilm_enabled => false
    }
  } else if [log_type] == "docker" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "ics-docker-%{+YYYY.MM.dd}"
      ilm_enabled => false
    }
  } else {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "ics-syslog-%{+YYYY.MM.dd}"
      ilm_enabled => false
    }
  }
}
